name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c처digo
        uses: actions/checkout@v3
      - name: Verificar a vers찾o do Python
        run: python3 --version

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c처digo
        uses: actions/checkout@v3
      - name: Executar o script de contagem em Python
        run: python3 count.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c처digo
        uses: actions/checkout@v3
      - name: Finalizar deploy
        run: echo "Finalizado"
