name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
stages:
  - build
  - test
  - deploy

jobs:
  build-job:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    deploy-job:
        stage: deploy
        script:
          - echo "Deploying the application"

     